[package]
name = "signalling_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-ws = "0.3.0"
dashmap = "6.1.0"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
uuid = "1.18.1"
